#!/usr/bin/env bash
#
# Drive the phase-0 lake skeleton (DATA_LAKE_DESIGN.md §11.1).
#
#   lake-skeleton.sh up        bring the stack up and bootstrap bucket + key
#   lake-skeleton.sh seed      generate the obviously-synthetic fixture set
#   lake-skeleton.sh verify    run the acceptance checks (bucket + catalog)
#   lake-skeleton.sh status    show containers, published ports, and disk use
#   lake-skeleton.sh down      stop the stack, keep the scratch data
#   lake-skeleton.sh destroy   stop the stack and delete every byte it owns
#
# `destroy` is the point, not an afterthought: under §11.0 this stack runs
# before encryption exists, so its safety rests on being genuinely disposable.
# If anything it wrote survives `destroy`, the guardrail has failed.
#
# All state lives under $LAKE_SKELETON_ROOT (default /scratch/lake-skeleton) —
# the scratch spindle, never /data, which is reserved for the real lake.

set -euo pipefail

ROOT="${LAKE_SKELETON_ROOT:-/scratch/lake-skeleton}"
PROJECT="aspirant-lake-skeleton"
BUCKET="${LAKE_S3_BUCKET:-lake-skeleton-bronze}"
KEY_NAME="lake-skeleton-rw"
ENV_FILE="$ROOT/lake-skeleton.env"

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$SRC_DIR/docker-compose.lake-skeleton.yml"

# Refuse to run against the real lake's volume. This is a structural stop, not
# a warning: the whole re-sequencing in §11.0 is only safe while the skeleton
# cannot touch /data.
case "$ROOT" in
  /data|/data/*)
    echo "refusing: LAKE_SKELETON_ROOT=$ROOT is on the real lake's volume (§11.0)" >&2
    exit 1
    ;;
esac

compose() {
  docker compose -p "$PROJECT" -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

garage_cli() {
  docker exec -e GARAGE_CONFIG_FILE=/etc/garage/garage.toml lake-skeleton-garage /garage "$@"
}

seed_config() {
  mkdir -p "$ROOT"/{config,garage/meta,garage/data,catalog}

  if [ ! -f "$ROOT/config/garage.toml" ]; then
    cat > "$ROOT/config/garage.toml" <<EOF
# Generated by lake-skeleton.sh — regenerated on a fresh 'up' after 'destroy'.
# Single node, replication_factor 1: this is a disposable skeleton, and Garage's
# own docs are explicit that a single-node deployment provides no redundancy.
replication_factor = 1
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "$(openssl rand -hex 32)"

[s3_api]
# 0.0.0.0 inside the container only — compose publishes no host port, so this
# listener is reachable from the project's own bridge network and nowhere else.
api_bind_addr = "[::]:3900"
s3_region = "garage"
EOF
    chmod 600 "$ROOT/config/garage.toml"
  fi

  if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<EOF
LAKE_SKELETON_ROOT=$ROOT
LAKE_S3_BUCKET=$BUCKET
LAKE_CATALOG_PASSWORD=$(openssl rand -hex 24)
# Filled in by 'up' once Garage issues the key.
LAKE_S3_ACCESS_KEY=pending
LAKE_S3_SECRET_KEY=pending
EOF
    chmod 600 "$ENV_FILE"
  fi
}

wait_healthy() {
  local svc="$1" tries=0
  until [ "$(docker inspect -f '{{.State.Health.Status}}' "lake-skeleton-$svc" 2>/dev/null)" = "healthy" ]; do
    tries=$((tries + 1))
    [ "$tries" -gt 60 ] && { echo "timed out waiting for $svc" >&2; return 1; }
    sleep 2
  done
}

bootstrap_garage() {
  # A fresh Garage node has no layout, and without a layout the S3 API answers
  # nothing. Assigning it is idempotent-by-check rather than by nature: applying
  # a layout twice bumps the version, so only do it when there are no roles yet.
  if ! garage_cli layout show 2>/dev/null | grep -q "$BUCKET" && \
     ! garage_cli status 2>/dev/null | grep -qE '^\s*[0-9a-f]{16}\s+.*\s(dc1)\s'; then
    local node_id
    node_id="$(garage_cli node id -q 2>/dev/null | cut -d@ -f1)"
    if [ -n "$node_id" ] && ! garage_cli layout show 2>/dev/null | grep -q "$node_id"; then
      garage_cli layout assign -z dc1 -c 50G "$node_id" >/dev/null
      garage_cli layout apply --version 1 >/dev/null
    fi
  fi

  garage_cli bucket info "$BUCKET" >/dev/null 2>&1 || garage_cli bucket create "$BUCKET" >/dev/null

  if ! garage_cli key info "$KEY_NAME" >/dev/null 2>&1; then
    garage_cli key create "$KEY_NAME" >/dev/null
    garage_cli bucket allow --read --write "$BUCKET" --key "$KEY_NAME" >/dev/null
  fi

  local key_id secret
  key_id="$(garage_cli key info "$KEY_NAME" --show-secret | awk '/Key ID:/ {print $3}')"
  secret="$(garage_cli key info "$KEY_NAME" --show-secret | awk '/Secret key:/ {print $3}')"
  sed -i "s|^LAKE_S3_ACCESS_KEY=.*|LAKE_S3_ACCESS_KEY=$key_id|" "$ENV_FILE"
  sed -i "s|^LAKE_S3_SECRET_KEY=.*|LAKE_S3_SECRET_KEY=$secret|" "$ENV_FILE"
}

case "${1:-}" in
  up)
    seed_config
    compose up -d garage catalog
    wait_healthy catalog
    # Garage reports unhealthy until its layout is applied, so bootstrap runs
    # against a started-but-not-yet-healthy node rather than waiting first.
    sleep 5
    bootstrap_garage
    wait_healthy garage
    echo "lake skeleton up — bucket '$BUCKET' on $ROOT (credentials in $ENV_FILE)"
    echo "next: 'lake-skeleton.sh seed' to generate fixtures, then 'verify'"
    ;;

  seed)
    compose --profile client run --rm duckdb /work/fixtures.py
    ;;

  verify)
    compose --profile client run --rm duckdb /work/verify.py
    ;;

  status)
    compose ps
    echo
    echo "published host ports (expect none):"
    docker ps --filter "label=com.docker.compose.project=$PROJECT" --format '{{.Names}}: {{.Ports}}'
    echo
    du -sh "$ROOT" 2>/dev/null || echo "$ROOT does not exist"
    ;;

  down)
    compose down
    echo "stack stopped; data retained at $ROOT"
    ;;

  destroy)
    compose down -v --remove-orphans || true
    # Postgres and Garage write as root/postgres inside the containers, so the
    # scratch tree is not owned by the invoking user.
    sudo rm -rf "$ROOT"
    echo "destroyed: containers, volumes, and $ROOT"
    ;;

  *)
    sed -n '3,15p' "${BASH_SOURCE[0]}"
    exit 1
    ;;
esac
