#!/usr/bin/env bash
#
# Drive the phase-0 lake skeleton (DATA_LAKE_DESIGN.md §11.1).
#
#   lake-skeleton.sh up        bring the stack up and bootstrap bucket + key
#   lake-skeleton.sh seed      generate the obviously-synthetic fixture set
#   lake-skeleton.sh verify    run the acceptance checks (bucket + catalog)
#   lake-skeleton.sh status    show containers, published ports, and disk use
#   lake-skeleton.sh down      stop the stack, keep the scratch data
#   lake-skeleton.sh destroy   stop the stack and delete every byte it owns
#
# `destroy` is the point, not an afterthought: under §11.0 this stack runs
# before encryption exists, so its safety rests on being genuinely disposable.
# If anything it wrote survives `destroy`, the guardrail has failed.
#
# All state lives under $LAKE_SKELETON_ROOT (default /scratch/lake-skeleton) —
# the scratch spindle, never /data, which is reserved for the real lake.

set -euo pipefail

ROOT="${LAKE_SKELETON_ROOT:-/scratch/lake-skeleton}"
PROJECT="aspirant-lake-skeleton"
BUCKET="${LAKE_S3_BUCKET:-lake-skeleton-bronze}"
KEY_NAME="lake-skeleton-rw"

# The explorer's read-only credentials (#2409-D4, system_3 #2542).
#
# These exist because the mediated lake bridge is only bounded if the
# CREDENTIALS are bounded. The operator authorised a mediated *read* path; a
# read-write key would make it a mediated read-write path with nothing marking
# the difference.
#
# They are issued HERE, by the bootstrap, and not by hand. Both credentials
# previously existed only as manual artifacts on one host: correct on that
# machine, absent from the repo, and silently gone after the destroy-and-
# recreate that LAKE_SKELETON.md makes an acceptance criterion. A bound that
# does not survive a rebuild is not a bound, and one that lives in a single
# host's memory cannot be reviewed.
RO_KEY_NAME="lake-skeleton-explorer-ro"
CATALOG_RO_ROLE="explorer_ro"

ENV_FILE="$ROOT/lake-skeleton.env"

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="$SRC_DIR/docker-compose.lake-skeleton.yml"

# Refuse to run against the real lake's volume. This is a structural stop, not
# a warning: the whole re-sequencing in §11.0 is only safe while the skeleton
# cannot touch /data.
case "$ROOT" in
  /data|/data/*)
    echo "refusing: LAKE_SKELETON_ROOT=$ROOT is on the real lake's volume (§11.0)" >&2
    exit 1
    ;;
esac

compose() {
  docker compose -p "$PROJECT" -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

garage_cli() {
  docker exec -e GARAGE_CONFIG_FILE=/etc/garage/garage.toml lake-skeleton-garage /garage "$@"
}

catalog_psql() {
  docker exec -i lake-skeleton-catalog \
    psql -v ON_ERROR_STOP=1 -U ducklake -d lake_catalog_skeleton "$@"
}

# Upsert a key into $ENV_FILE.
#
# NOT a bare `sed -i "s|^KEY=.*|KEY=$v|"`. That is what the file used before,
# and it silently does nothing when the key is absent — which is exactly the
# case for every env file created before this change, since seed_config only
# writes the template when the file does not already exist. The result would be
# a bootstrap that reports success while leaving the explorer with no
# credentials, on precisely the hosts that already exist.
env_set() {
  local key="$1" value="$2"
  if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
}

seed_config() {
  mkdir -p "$ROOT"/{config,garage/meta,garage/data,catalog}

  if [ ! -f "$ROOT/config/garage.toml" ]; then
    cat > "$ROOT/config/garage.toml" <<EOF
# Generated by lake-skeleton.sh — regenerated on a fresh 'up' after 'destroy'.
# Single node, replication_factor 1: this is a disposable skeleton, and Garage's
# own docs are explicit that a single-node deployment provides no redundancy.
replication_factor = 1
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "lmdb"

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "$(openssl rand -hex 32)"

[s3_api]
# 0.0.0.0 inside the container only — compose publishes no host port, so this
# listener is reachable from the project's own bridge network and nowhere else.
api_bind_addr = "[::]:3900"
s3_region = "garage"
EOF
    chmod 600 "$ROOT/config/garage.toml"
  fi

  if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" <<EOF
LAKE_SKELETON_ROOT=$ROOT
LAKE_S3_BUCKET=$BUCKET
LAKE_CATALOG_PASSWORD=$(openssl rand -hex 24)
# Filled in by 'up' once Garage issues the keys.
LAKE_S3_ACCESS_KEY=pending
LAKE_S3_SECRET_KEY=pending
# The explorer's read-only pair — read by docker-compose.yml's explorer-api.
EXPLORER_S3_ACCESS_KEY=pending
EXPLORER_S3_SECRET_KEY=pending
LAKE_CATALOG_RO_PASSWORD=pending
LAKE_CATALOG_RO_DSN=pending
EOF
    chmod 600 "$ENV_FILE"
  fi
}

wait_healthy() {
  local svc="$1" tries=0
  until [ "$(docker inspect -f '{{.State.Health.Status}}' "lake-skeleton-$svc" 2>/dev/null)" = "healthy" ]; do
    tries=$((tries + 1))
    [ "$tries" -gt 60 ] && { echo "timed out waiting for $svc" >&2; return 1; }
    sleep 2
  done
}

bootstrap_garage() {
  # A fresh Garage node has no layout, and without a layout the S3 API answers
  # nothing. Assigning it is idempotent-by-check rather than by nature: applying
  # a layout twice bumps the version, so only do it when there are no roles yet.
  if ! garage_cli layout show 2>/dev/null | grep -q "$BUCKET" && \
     ! garage_cli status 2>/dev/null | grep -qE '^\s*[0-9a-f]{16}\s+.*\s(dc1)\s'; then
    local node_id
    node_id="$(garage_cli node id -q 2>/dev/null | cut -d@ -f1)"
    if [ -n "$node_id" ] && ! garage_cli layout show 2>/dev/null | grep -q "$node_id"; then
      garage_cli layout assign -z dc1 -c 50G "$node_id" >/dev/null
      garage_cli layout apply --version 1 >/dev/null
    fi
  fi

  garage_cli bucket info "$BUCKET" >/dev/null 2>&1 || garage_cli bucket create "$BUCKET" >/dev/null

  if ! garage_cli key info "$KEY_NAME" >/dev/null 2>&1; then
    garage_cli key create "$KEY_NAME" >/dev/null
    garage_cli bucket allow --read --write "$BUCKET" --key "$KEY_NAME" >/dev/null
  fi

  # The explorer's key: --read, and deliberately no --write.
  #
  # Re-granted on every run even when the key already exists. Creation and
  # permission are separate operations in Garage, so a key that exists proves
  # nothing about what it is allowed to do — and `--read` is idempotent, so
  # asserting it costs nothing and closes the window where a key was created
  # here and widened elsewhere.
  if ! garage_cli key info "$RO_KEY_NAME" >/dev/null 2>&1; then
    garage_cli key create "$RO_KEY_NAME" >/dev/null
  fi
  garage_cli bucket allow --read "$BUCKET" --key "$RO_KEY_NAME" >/dev/null
  garage_cli bucket deny --write "$BUCKET" --key "$RO_KEY_NAME" >/dev/null 2>&1 || true

  local key_id secret ro_key_id ro_secret
  key_id="$(garage_cli key info "$KEY_NAME" --show-secret | awk '/Key ID:/ {print $3}')"
  secret="$(garage_cli key info "$KEY_NAME" --show-secret | awk '/Secret key:/ {print $3}')"
  env_set LAKE_S3_ACCESS_KEY "$key_id"
  env_set LAKE_S3_SECRET_KEY "$secret"

  ro_key_id="$(garage_cli key info "$RO_KEY_NAME" --show-secret | awk '/Key ID:/ {print $3}')"
  ro_secret="$(garage_cli key info "$RO_KEY_NAME" --show-secret | awk '/Secret key:/ {print $3}')"
  # Written under the names the main compose file reads for explorer-api, so
  # the service is bound to THIS key rather than to whatever the environment
  # happened to hold. That binding is the second half of the guarantee: issuing
  # a read-only key changes nothing if the consumer is handed a different one.
  env_set EXPLORER_S3_ACCESS_KEY "$ro_key_id"
  env_set EXPLORER_S3_SECRET_KEY "$ro_secret"
}

# SELECT-only catalog role, for the same reason and with the same history: it
# existed on one host and in no script.
bootstrap_catalog_role() {
  local pw
  pw="$(grep '^LAKE_CATALOG_RO_PASSWORD=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)"
  if [ -z "$pw" ] || [ "$pw" = "pending" ]; then
    pw="$(openssl rand -hex 24)"
    env_set LAKE_CATALOG_RO_PASSWORD "$pw"
  fi

  # Idempotent by construction: CREATE ROLE fails if it exists, so the DO block
  # branches, and the GRANTs are re-asserted every run for the same reason the
  # Garage --read is.
  catalog_psql <<SQL >/dev/null
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$CATALOG_RO_ROLE') THEN
    CREATE ROLE $CATALOG_RO_ROLE LOGIN;
  END IF;
END
\$\$;
ALTER ROLE $CATALOG_RO_ROLE WITH PASSWORD '$pw';
REVOKE ALL ON SCHEMA public FROM $CATALOG_RO_ROLE;
GRANT CONNECT ON DATABASE lake_catalog_skeleton TO $CATALOG_RO_ROLE;
GRANT USAGE ON SCHEMA public TO $CATALOG_RO_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $CATALOG_RO_ROLE;
-- Tables created later by the DuckLake catalog must inherit SELECT, or the
-- role is read-only today and blind tomorrow.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $CATALOG_RO_ROLE;
SQL

  env_set LAKE_CATALOG_RO_DSN \
    "postgresql://$CATALOG_RO_ROLE:$pw@lake-skeleton-catalog:5432/lake_catalog_skeleton"
}

# The write-denial proof lives in lake_skeleton_verify.py, not here.
#
# It belongs with the other acceptance checks because that is what it is: the
# claim "the explorer holds a read-only key" is exactly as strong as the
# attempt to write with it. Putting it there also keeps it on the stack's own
# client image — an earlier draft of this ran `amazon/aws-cli` via `docker run`,
# which adds a ~400MB pull to the bootstrap of a deliberately disposable
# skeleton, over a link the standing constraints call slow and lossy.
#
# Run it with: scripts/lake-skeleton.sh verify

case "${1:-}" in
  up)
    seed_config
    compose up -d garage catalog
    wait_healthy catalog
    # Garage reports unhealthy until its layout is applied, so bootstrap runs
    # against a started-but-not-yet-healthy node rather than waiting first.
    sleep 5
    bootstrap_garage
    wait_healthy garage
    bootstrap_catalog_role
    echo "lake skeleton up — bucket '$BUCKET' on $ROOT (credentials in $ENV_FILE)"
    echo "explorer read-only credentials issued: '$RO_KEY_NAME' + catalog role '$CATALOG_RO_ROLE'"
    echo "their read-only-ness is PROVEN by 'verify', not asserted here — run it next"
    echo "next: 'lake-skeleton.sh seed' to generate fixtures, then 'verify'"
    ;;

  seed)
    compose --profile client run --rm duckdb /work/fixtures.py
    ;;

  verify)
    compose --profile client run --rm duckdb /work/verify.py
    ;;

  status)
    compose ps
    echo
    echo "published host ports (expect none):"
    docker ps --filter "label=com.docker.compose.project=$PROJECT" --format '{{.Names}}: {{.Ports}}'
    echo
    du -sh "$ROOT" 2>/dev/null || echo "$ROOT does not exist"
    ;;

  down)
    compose down
    echo "stack stopped; data retained at $ROOT"
    ;;

  destroy)
    compose down -v --remove-orphans || true
    # Postgres and Garage write as root/postgres inside the containers, so the
    # scratch tree is not owned by the invoking user.
    sudo rm -rf "$ROOT"
    echo "destroyed: containers, volumes, and $ROOT"
    ;;

  *)
    sed -n '3,15p' "${BASH_SOURCE[0]}"
    exit 1
    ;;
esac
